[2025-01-17T10:27:13.542+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T10:27:13.603+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T10:24:53.472529+00:00 [queued]>
[2025-01-17T10:27:13.699+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T10:24:53.472529+00:00 [queued]>
[2025-01-17T10:27:13.704+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T10:27:13.825+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_data_to_duckdb> on 2025-01-17 10:24:53.472529+00:00
[2025-01-17T10:27:13.864+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T10:27:13.871+0000] {standard_task_runner.py:72} INFO - Started process 428 to run task
[2025-01-17T10:27:13.865+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_data_to_duckdb', 'save_data_to_duckdb', 'manual__2025-01-17T10:24:53.472529+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/api_duckdb_dag.py', '--cfg-path', '/tmp/tmpc9jiq9qk']
[2025-01-17T10:27:13.880+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask save_data_to_duckdb
[2025-01-17T10:27:14.255+0000] {task_command.py:467} INFO - Running <TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T10:24:53.472529+00:00 [running]> on host 394999114d74
[2025-01-17T10:27:14.794+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_data_to_duckdb' AIRFLOW_CTX_TASK_ID='save_data_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T10:24:53.472529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T10:24:53.472529+00:00'
[2025-01-17T10:27:14.798+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T10:27:14.800+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T10:27:14.807+0000] {logging_mixin.py:190} INFO - Current task name:save_data_to_duckdb state:running start_date:2025-01-17 10:27:13.605747+00:00
[2025-01-17T10:27:14.815+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb and current dag run status:running
[2025-01-17T10:27:14.817+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T10:27:15.060+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_duckdb_dag.py", line 45, in save_data_to_duckdb
    conn = duckdb.connect(DUCKDB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 426). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T10:27:15.140+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-17T10:27:15.145+0000] {logging_mixin.py:190} INFO - Task start:2025-01-17 10:27:13.605747+00:00 end:2025-01-17 10:27:15.138313+00:00 duration:1.532566
[2025-01-17T10:27:15.149+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_data_to_duckdb> dag:<DAG: user_data_to_duckdb> dagrun:<DagRun user_data_to_duckdb @ 2025-01-17 10:24:53.472529+00:00: manual__2025-01-17T10:24:53.472529+00:00, state:running, queued_at: 2025-01-17 10:24:53.901349+00:00. externally triggered: True>
[2025-01-17T10:27:15.152+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 426). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T10:27:15.154+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=user_data_to_duckdb, task_id=save_data_to_duckdb, run_id=manual__2025-01-17T10:24:53.472529+00:00, execution_date=20250117T102453, start_date=20250117T102713, end_date=20250117T102715
[2025-01-17T10:27:15.235+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T10:27:15.238+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task save_data_to_duckdb (IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 426). See also https://duckdb.org/docs/connect/concurrency; 428)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_duckdb_dag.py", line 45, in save_data_to_duckdb
    conn = duckdb.connect(DUCKDB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 426). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T10:27:15.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-17T10:27:15.499+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T10:27:15.514+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
