[2025-01-20T07:07:18.458+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T07:07:18.579+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T07:07:18.681+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T07:07:18.688+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-20T07:07:18.757+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_transform> on 2025-01-19 00:00:00+00:00
[2025-01-20T07:07:18.778+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T07:07:18.784+0000] {standard_task_runner.py:72} INFO - Started process 273 to run task
[2025-01-20T07:07:18.794+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_data_to_duckdb', 'run_dbt_transform', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/api_duckdb_dag.py', '--cfg-path', '/tmp/tmpi50yy9cg']
[2025-01-20T07:07:18.796+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask run_dbt_transform
[2025-01-20T07:07:19.015+0000] {task_command.py:467} INFO - Running <TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [running]> on host f1a6bf7b32bb
[2025-01-20T07:07:19.355+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_data_to_duckdb' AIRFLOW_CTX_TASK_ID='run_dbt_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-20T07:07:19.358+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T07:07:19.359+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T07:07:19.362+0000] {logging_mixin.py:190} INFO - Current task name:run_dbt_transform state:running start_date:2025-01-20 07:07:18.584435+00:00
[2025-01-20T07:07:19.363+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb and current dag run status:running
[2025-01-20T07:07:19.365+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T07:07:19.367+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T07:07:19.372+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt_models &&         dbt run --profiles-dir /opt/***/dbt/profiles.yml/ --target dev\n        ']
[2025-01-20T07:07:19.447+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T07:07:30.975+0000] {subprocess.py:106} INFO - [0m07:07:30  Running with dbt=1.9.1
[2025-01-20T07:07:35.313+0000] {subprocess.py:106} INFO - [0m07:07:35  Registered adapter: duckdb=1.9.1
[2025-01-20T07:07:37.027+0000] {subprocess.py:106} INFO - [0m07:07:37  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-01-20T07:07:37.029+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-01-20T07:07:37.030+0000] {subprocess.py:106} INFO - - models.my_dbt_project
[2025-01-20T07:07:37.780+0000] {subprocess.py:106} INFO - [0m07:07:37  Found 424 macros
[2025-01-20T07:07:37.789+0000] {subprocess.py:106} INFO - [0m07:07:37  Nothing to do. Try checking your model configs and model specification args
[2025-01-20T07:07:55.394+0000] {job.py:229} INFO - Heartbeat recovered after 21.22 seconds
[2025-01-20T07:07:56.378+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-20T07:07:56.593+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T07:07:56.607+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_data_to_duckdb, task_id=run_dbt_transform, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250120T070718, end_date=20250120T070756
[2025-01-20T07:07:56.713+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-20T07:07:56.722+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-20T07:07:56.725+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb queued_at:2025-01-20 07:01:32.824646+00:00
[2025-01-20T07:07:56.729+0000] {logging_mixin.py:190} INFO - Task hostname:f1a6bf7b32bb operator:BashOperator
[2025-01-20T07:07:56.873+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T07:07:56.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-20T08:10:22.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T08:10:22.872+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T08:10:22.898+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T08:10:22.900+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-20T08:10:22.941+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_transform> on 2025-01-19 00:00:00+00:00
[2025-01-20T08:10:22.963+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T08:10:22.967+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-01-20T08:10:22.968+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_data_to_duckdb', 'run_dbt_transform', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/api_duckdb_dag.py', '--cfg-path', '/tmp/tmpx7290qx7']
[2025-01-20T08:10:22.971+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask run_dbt_transform
[2025-01-20T08:10:23.107+0000] {task_command.py:467} INFO - Running <TaskInstance: user_data_to_duckdb.run_dbt_transform scheduled__2025-01-19T00:00:00+00:00 [running]> on host af5c9462b200
[2025-01-20T08:10:23.390+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_data_to_duckdb' AIRFLOW_CTX_TASK_ID='run_dbt_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-20T08:10:23.393+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T08:10:23.401+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T08:10:23.406+0000] {logging_mixin.py:190} INFO - Current task name:run_dbt_transform state:running start_date:2025-01-20 08:10:22.873171+00:00
[2025-01-20T08:10:23.413+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb and current dag run status:running
[2025-01-20T08:10:23.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T08:10:23.439+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T08:10:23.446+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt_models &&         dbt run --profiles-dir /opt/***/dbt/profiles.yml --target dev\n        ']
[2025-01-20T08:10:23.498+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T08:10:31.004+0000] {subprocess.py:106} INFO - [0m08:10:31  Running with dbt=1.9.1
[2025-01-20T08:10:32.810+0000] {subprocess.py:106} INFO - [0m08:10:32  Registered adapter: duckdb=1.9.1
[2025-01-20T08:10:33.185+0000] {subprocess.py:106} INFO - [0m08:10:33  Unable to do partial parsing because a project config has changed
[2025-01-20T08:10:35.910+0000] {subprocess.py:106} INFO - [0m08:10:35  Encountered an error:
[2025-01-20T08:10:35.911+0000] {subprocess.py:106} INFO - Compilation Error
[2025-01-20T08:10:35.912+0000] {subprocess.py:106} INFO -   Model 'model.my_dbt_project.transform_users' (models/transform_users.sql) depends on a source named 'my_dbt_profile.users' which was not found
[2025-01-20T08:10:39.134+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-01-20T08:10:39.181+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-20T08:10:39.223+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-20T08:10:39.225+0000] {logging_mixin.py:190} INFO - Task start:2025-01-20 08:10:22.873171+00:00 end:2025-01-20 08:10:39.221821+00:00 duration:16.34865
[2025-01-20T08:10:39.227+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_dbt_transform> dag:<DAG: user_data_to_duckdb> dagrun:<DagRun user_data_to_duckdb @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-20 08:08:54.720969+00:00. externally triggered: False>
[2025-01-20T08:10:39.228+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-01-20T08:10:39.229+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=user_data_to_duckdb, task_id=run_dbt_transform, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250120T081022, end_date=20250120T081039
[2025-01-20T08:10:39.290+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T08:10:39.291+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task run_dbt_transform (Bash command failed. The command returned a non-zero exit code 2.; 215)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-20T08:10:39.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-20T08:10:39.396+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T08:10:39.400+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
