[2025-01-17T11:45:55.765+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T11:45:56.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T11:27:35.475863+00:00 [queued]>
[2025-01-17T11:45:56.080+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T11:27:35.475863+00:00 [queued]>
[2025-01-17T11:45:56.085+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-17T11:45:56.168+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_data_to_duckdb> on 2025-01-17 11:27:35.475863+00:00
[2025-01-17T11:45:56.197+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=276) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T11:45:56.207+0000] {standard_task_runner.py:72} INFO - Started process 289 to run task
[2025-01-17T11:45:56.203+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_data_to_duckdb', 'save_data_to_duckdb', 'manual__2025-01-17T11:27:35.475863+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/api_duckdb_dag.py', '--cfg-path', '/tmp/tmp6t2mkxz4']
[2025-01-17T11:45:56.215+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask save_data_to_duckdb
[2025-01-17T11:45:56.447+0000] {task_command.py:467} INFO - Running <TaskInstance: user_data_to_duckdb.save_data_to_duckdb manual__2025-01-17T11:27:35.475863+00:00 [running]> on host 78d3b8284409
[2025-01-17T11:45:56.808+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_data_to_duckdb' AIRFLOW_CTX_TASK_ID='save_data_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T11:27:35.475863+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T11:27:35.475863+00:00'
[2025-01-17T11:45:56.817+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T11:45:56.818+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T11:45:56.819+0000] {logging_mixin.py:190} INFO - Current task name:save_data_to_duckdb state:running start_date:2025-01-17 11:45:56.045272+00:00
[2025-01-17T11:45:56.819+0000] {logging_mixin.py:190} INFO - Dag name:user_data_to_duckdb and current dag run status:running
[2025-01-17T11:45:56.820+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T11:45:56.870+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_duckdb_dag.py", line 45, in save_data_to_duckdb
    conn = duckdb.connect(DUCKDB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 287). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T11:45:56.929+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-17T11:45:56.930+0000] {logging_mixin.py:190} INFO - Task start:2025-01-17 11:45:56.045272+00:00 end:2025-01-17 11:45:56.928039+00:00 duration:0.882767
[2025-01-17T11:45:56.931+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_data_to_duckdb> dag:<DAG: user_data_to_duckdb> dagrun:<DagRun user_data_to_duckdb @ 2025-01-17 11:27:35.475863+00:00: manual__2025-01-17T11:27:35.475863+00:00, state:running, queued_at: 2025-01-17 11:27:35.592677+00:00. externally triggered: True>
[2025-01-17T11:45:56.933+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 287). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T11:45:56.934+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=user_data_to_duckdb, task_id=save_data_to_duckdb, run_id=manual__2025-01-17T11:27:35.475863+00:00, execution_date=20250117T112735, start_date=20250117T114556, end_date=20250117T114556
[2025-01-17T11:45:56.966+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T11:45:56.967+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 104 for task save_data_to_duckdb (IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 287). See also https://duckdb.org/docs/connect/concurrency; 289)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_duckdb_dag.py", line 45, in save_data_to_duckdb
    conn = duckdb.connect(DUCKDB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/apidata/my_duckdb_database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 287). See also https://duckdb.org/docs/connect/concurrency
[2025-01-17T11:45:57.036+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-17T11:45:57.086+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T11:45:57.094+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
